Make clu run as non root except for required

diff --git a/clu b/clu
--- a/clu
+++ b/clu
@@ -85,6 +85,14 @@ USAGE
     exit
 }
 
+# Check SUDO/root status
+# --------------------------------------------------------------------------------------------------
+if [[ "$(whoami)" == "root" ]]; then
+    log::ls "${red}Error: root user detected!${none}"
+    log::ls "${yellow}Run with user that has passwordless sudo priviledges but not as root${none}"
+    exit 1
+fi
+
 # Parse commands
 # --------------------------------------------------------------------------------------------------
 [[ $# -eq 0 ]] && core::usage
