Configuring update machine switching

diff --git a/lib/flake b/lib/flake
--- a/lib/flake
+++ b/lib/flake
@@ -28,6 +28,7 @@ flake::switch()
     local machine_path="machines/$MACHINE"
     local flake_local="$machine_path/flake.nix"
     local flake_local_lock="$machine_path/flake.lock"
+    log::header0 "Switching to machine ${cyan}$MACHINE${none}"
 
     # Check if the given machine exists
     [[ "$MACHINE" == "" ]] && log::fatal "Machine name not given"
@@ -66,9 +67,10 @@ flake::restore()
     fi
 }
 
-# Cleanup if interrupted or failed after changing variables
-flake::cleanup()
+# Cleanup trap function. Typically not used as the local functions will have their own which will
+# call flake::restore directly
+flake::trap()
 {
     flake::restore
-    exit 0
+    exit 1
 }
diff --git a/lib/update b/lib/update
--- a/lib/update
+++ b/lib/update
@@ -58,7 +58,8 @@ update::flake()
     core::title
     log::header1 "Update flake"
 
-    nix flake update
+    echo "${orange}TODO: not implemented!${none}" && exit 1
+    #nix flake update
 }
 
 
@@ -68,15 +69,11 @@ update::profile()
 {
     core::title
     log::header1 "Update install profile"
+    echo "${orange}TODO: not implemented!${none}" && exit 1
 
     log::ln "Switching install profile to ${cyan}${@}${none}"
     utils::replace str "profile" "${@}" "${FLAKE_ARGS}"
     git add "${FLAKE_ARGS}"
-
-    _update::preUpdate
-    _update::removeUserXfceConfigs
-    _update::updateSystem
-    _update::postUpdate
 }
 
 # Update the system with the system configuration changes
@@ -85,24 +82,34 @@ update::system()
 {
     core::title
     log::header1 "Update system version"
+    _update::pre
 
     # Cleanup the .config/xfce4 directories to ensure new settings don't conflict
-    _update::preUpdate
     local arg=$1; shift
     if [[ "$arg" == "reset-xfce" ]]; then
         _update::removeUserXfceConfigs
     fi
-    _update::updateSystem $@
-    _update::postUpdate
+
+    # Execute update
+    local impure=""
+    [[ "$@" == "impure" ]] && impure="--impure"
+    nixos-rebuild switch $impure --flake "path:/etc/nixos#system"
+
+    _update::post
 }
 
-_update::preUpdate()
+# Pre update operations
+_update::pre()
 {
     log::ln "Removing ${cyan}/nix/files.lock${none} to permit files update"
     rm -f /nix/files.lock
 
     log::ln "Shutting down ${cyan}xfconfd${none} to avoid conflicts"
     pkill xfconfd
+
+    flake::switch "$MACHINE"
+
+    trap _update::trap INT KILL
 }
 
 # Remove user xfce configurations to get a clean point to start from
@@ -117,17 +124,18 @@ _update::removeUserXfceConfigs()
     done
 }
 
-# Trigger the Nix flake based system update
-_update::updateSystem()
+# Post update operations
+_update::post()
 {
-    local impure=""
-    [[ "$@" == "impure" ]] && impure="--impure"
+    flake::restore
 
-    nixos-rebuild switch $impure --flake "path:/etc/nixos#system"
-}
-
-_update::postUpdate()
-{
     log::ln "Adding ${cyan}/nix/files.lock${none} to block files updates during reboots"
     touch /nix/files.lock
+}
+
+# Cleanup trap function
+_update::trap()
+{
+    _update::post
+    exit 1
 }
