Make installer locally testable

diff --git a/lib/install b/lib/install
--- a/lib/install
+++ b/lib/install
@@ -6,6 +6,28 @@
 #
 # --------------------------------------------------------------------------------------------------
 
+# Usage for the install command and its sub commands
+# --------------------------------------------------------------------------------------------------
+install::usage()
+{
+    cat <<USAGE
+Usage:
+  install [OPTIONS] [COMMAND] [ARGS...]
+
+Options:
+  -h, --help        Print out usage
+
+Commands:
+  install [PATH]    Execute the installer with an optional alternate nixos-config destination
+USAGE
+
+    log::ln "\nExamples:"
+    log::subln "Launch installer: ${green}sudo ./${SCRIPT} install${none}"
+    log::subln "Launch installer with alternate nixos-config path: ${green}sudo ./${SCRIPT} install tmp${none}"
+    echo
+    exit
+}
+
 # Partition disk and mount for install at ${ROOT_MOUNT}
 install::prepare_disk()
 {
@@ -209,29 +231,31 @@ install::config_system()
 
     # Execute the NixOS install
     # ----------------------------------------------------------------------------------------------
-    log::header1 "Installing NixOS configuration"
-    echo -e ":: Pre-populating the Nix Store..."
-    nix copy --all --no-check-sigs --offline --to local?root="${ROOT_MOUNT}"
+    if [ "x$TESTING" != "xy" ]; then
+        log::header1 "Installing NixOS configuration"
+        echo -e ":: Pre-populating the Nix Store..."
+        nix copy --all --no-check-sigs --offline --to local?root="${ROOT_MOUNT}"
 
-    # Run the installer: $NIXOS_CONFIG_DIR will usually be /mnt/etc/nixos
-    # nixos-install --no-root-passwd --no-channel-copy --flake /mnt/etc/nixos#system
-    nixos-install --no-root-passwd --no-channel-copy --flake "${NIXOS_CONFIG_DIR}#system"
-    if [ $? -ne 0 ]; then
-        echo -e ":: ${red}Failure building the install flake${none}"
-        echo -e "   1. Fix the flake issue at ${cyan}${NIXOS_CONIFG}${none}"
-        echo -e "   2. Rerun: ${cyan}nixos-install --no-root-passwd --no-channel-copy --flake ${NIXOS_CONFIG_DIR}#system${none}"
+        # Run the installer: $NIXOS_CONFIG_DIR will usually be /mnt/etc/nixos
+        # nixos-install --no-root-passwd --no-channel-copy --flake /mnt/etc/nixos#system
+        nixos-install --no-root-passwd --no-channel-copy --flake "${NIXOS_CONFIG_DIR}#system"
+        if [ $? -ne 0 ]; then
+            echo -e ":: ${red}Failure building the install flake${none}"
+            echo -e "   1. Fix the flake issue at ${cyan}${NIXOS_CONIFG}${none}"
+            echo -e "   2. Rerun: ${cyan}nixos-install --no-root-passwd --no-channel-copy --flake ${NIXOS_CONFIG_DIR}#system${none}"
+        fi
+
+        lockfile="${ROOT_MOUNT}/nix/files.lock"
+        echo -e ":: Adding files lock file ${lockfile} to avoid file automation on every boot"
+        touch "${lockfile}"
+
+        echo -e ":: Update the swap entry to use the device UUID"
+        SWAP_UUID=$(blkid -s UUID -o value ${PART_SWAP})
+        utils::replace str "${PART_SWAP}" "/dev/disk/by-uuid/${SWAP_UUID}" "${NIXOS_CONFIG_DIR}/hardware-configuration.nix"
+        pushd ${NIXOS_CONFIG_DIR}
+        git add hardware-configuration.nix -f
+        popd
     fi
-
-    lockfile="${ROOT_MOUNT}/nix/files.lock"
-    echo -e ":: Adding files lock file ${lockfile} to avoid file automation on every boot"
-    touch "${lockfile}"
-
-    echo -e ":: Update the swap entry to use the device UUID"
-    SWAP_UUID=$(blkid -s UUID -o value ${PART_SWAP})
-    utils::replace str "${PART_SWAP}" "/dev/disk/by-uuid/${SWAP_UUID}" "${NIXOS_CONFIG_DIR}/hardware-configuration.nix"
-    pushd ${NIXOS_CONFIG_DIR}
-    git add hardware-configuration.nix -f
-    popd
 
     echo
     echo -e ":: ${yellow}1. Power down your system:${none} sudo poweroff"
@@ -243,14 +267,26 @@ install::config_system()
 # --------------------------------------------------------------------------------------------------
 install::run()
 {
-    core::title
-
     # Default installer values
     # ----------------------------------------------------------------------------------------------
-    ROOT_MOUNT='/mnt'
-    NIXOS_CONFIG_DIR="${ROOT_MOUNT}/etc/nixos"
+    #utils::help "$@" "install::usage"
+    core::title
+
+    # Optionally enable testing with an alternate configuration destination
+    args=($@)
+    if [[ "${args[0]}" != "" ]]; then
+        log::header0 "Testing installer with alternate nixos_config destination: ${cyan}${args[0]}${none}"
+        utils::read PROCEED 'Do you want to proceed with alternate install path' 'n'
+        [[ $PROCEED != "y" ]] && exit || mkdir -p "${args[0]}"
+        NIXOS_CONFIG_DIR="${args[0]}"
+        TESTING="y"
+    fi
+
+    ROOT_MOUNT="/mnt"
+    DEFAULT="${DEFAULT:-n}"
+    TESTING="${TESTING:-n}"
+    NIXOS_CONFIG_DIR="${NIXOS_CONFIG_DIR:-${ROOT_MOUNT}/etc/nixos}"
     SCSI=0
-    DEFAULT='n'
     TIMEZONE='America/Boise'
 
     # Network settings
@@ -325,7 +361,7 @@ install::run()
     # Drop out debug variables if in debug mode
     # ----------------------------------------------------------------------------------------------
     log::ln_d "Entering debug mode"
-    log::ln_d "Debug lins are prefixed with violet ${violet}>>${none}"
+    log::ln_d "Debug lines are prefixed with violet ${violet}>>${none}"
     log::vars
 
     # Collect install destination choice from user
@@ -456,6 +492,7 @@ install::run()
 
     # Networking settings
     log::subln3 "hostname=${cyan}${HOSTNAME}${none}"
+    log::subln3 "network_bridge=${cyan}${NETWORK_BRIDGE}${none}"
     log::subln3 "static_ip=${cyan}${STATIC_IP}${none}"
     log::subln3 "gateway=${cyan}${GATEWAY}${none}"
     log::subln3 "primary_dns=${cyan}${PRIMARY_DNS}${none}"
@@ -483,7 +520,9 @@ install::run()
     log::subln3 "EFI=${cyan}${EFI}${none}"
 
     # Partition the target disk and mount it for deployment
-    install::prepare_disk
+    if [ "x$TESTING" != "xy" ]; then
+        install::prepare_disk
+    fi
 
     # Take user selections and apply to NixOS configuration
     install::config_system
