Built out a nix-locate replacement

diff --git a/lib/utils b/lib/utils
--- a/lib/utils
+++ b/lib/utils
@@ -11,6 +11,41 @@ cyan="\e[1;36m"
 green="\e[1;32m"
 yellow="\e[1;33m"
 
+# Temporary file for reading command errors
+ERRFILE=/tmp/clu.err
+
+# Example retry using ERRFILE
+# local retry=true
+# while [ "$retry" == true ]; do
+#     nix-locate "$@" 2>$ERRFILE
+#     if [ $? -ne 0 ]; then
+#         local err=$(<$ERRFILE)
+#         if [[ "$err" == *"'/root/.cache/nix-index/files' failed"* ]]; then
+#             nix-index
+#         fi
+#     else
+#         retry=false
+#     fi
+# done
+
+# Check if the given binary is installed
+#
+# ### Params
+# - $1 binary to check for
+# - $2 message if the binary doesn't exist
+#
+# ### Examples
+# utils::exists "nix-locate" "${cyan}nix-index${none} package must be installed"
+utils::exists()
+{
+    local target="$1"
+    local msg="$2"
+
+    if [ ! $(which "$target" 2>/dev/null) ]; then
+        log::fatal "$msg"
+    fi
+}
+
 # Common exit code for debug logging
 utils::exit()
 {
